In [1]:
# -*- encoding:urf-8 -*-
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Handle table like and matrices
import pandas as pd
import numpy as np

# Modeling Helper
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
import missingno as msno

# Configure visualization
%matplotlib inline
mpl.style.use('ggplot')
sns.set_style('white')
pylab.rcParams['figure.figsize'] = 8,6

train_path = '../input/train.csv'
test_path = '../input/test.csv'
hol_path = '../input/holiday.csv'
train_date_path = '../input/train_date.csv'
cache_path = '../input/cache/'
output_path = '../output/'
train_valid_path = '../input/validate/'
train_new_path = 'train_new_total.csv'
train_new = pd.read_csv(train_new_path)
test = pd.read_csv(test_path)
do_not_use_class = [1516,3005,3424]

In [2]:
# saleCount mean
coord  = train_new.groupby('Class',as_index=False)['saleCount'].agg({'saleCount_mean':'mean'})
train_new = pd.merge(train_new, coord, on='Class', how = 'left')
coord  = train_new.groupby('Class',as_index=False)['saleCount'].agg({'saleCount_std':'std'})
train_new = pd.merge(train_new, coord, on='Class', how = 'left')
train_new

,Class,parClass,SaleDate,saleCount,Coupon,holidayCluster,disHoliday,month,dayOfWeek,dayOfYear,...,holDaySaleCount_mean,holDaySaleCount_max,holDaySaleCount_min,wkHolRatio,bonusRatio,bonusHolRatio,bonusNotHolRatio,bonusWeekProb,saleCount_mean,saleCount_std
0,1001,10,2015-01-01,3,0.0,3,1.0,1,3,1,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
1,1001,10,2015-01-02,6,0.0,3,1.0,1,4,2,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
2,1001,10,2015-01-03,7,0.0,3,1.0,1,5,3,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
3,1001,10,2015-01-04,5,0.0,1,0.5,1,6,4,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
4,1001,10,2015-01-05,9,0.0,1,0.3,1,0,5,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
5,1001,10,2015-01-06,5,0.0,1,0.3,1,1,6,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
6,1001,10,2015-01-07,28,0.0,1,0.0,1,2,7,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
7,1001,10,2015-01-08,7,0.0,1,0.0,1,3,8,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
8,1001,10,2015-01-09,4,0.0,1,0.0,1,4,9,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
9,1001,10,2015-01-10,4,0.0,2,0.0,1,5,10,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
10,1001,10,2015-01-11,3,0.0,2,0.0,1,6,11,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
11,1001,10,2015-01-12,12,0.0,1,0.0,1,0,12,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
12,1001,10,2015-01-13,5,0.0,1,0.0,1,1,13,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
13,1001,10,2015-01-14,16,0.0,1,0.0,1,2,14,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
14,1001,10,2015-01-15,9,0.0,1,0.0,1,3,15,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
15,1001,10,2015-01-16,9,0.0,1,0.0,1,4,16,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
16,1001,10,2015-01-17,3,0.0,2,0.0,1,5,17,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
17,1001,10,2015-01-18,5,0.0,2,0.0,1,6,18,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
18,1001,10,2015-01-19,4,0.0,1,0.0,1,0,19,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
19,1001,10,2015-01-20,9,0.0,1,0.0,1,1,20,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
20,1001,10,2015-01-21,25,0.0,1,0.0,1,2,21,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
21,1001,10,2015-01-22,6,0.0,1,0.0,1,3,22,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
22,1001,10,2015-01-23,7,0.0,1,0.0,1,4,23,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
23,1001,10,2015-01-24,2,0.0,2,0.0,1,5,24,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
24,1001,10,2015-01-25,5,0.0,2,0.0,1,6,25,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
25,1001,10,2015-01-26,13,0.0,1,0.0,1,0,26,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
26,1001,10,2015-01-27,12,0.0,1,0.0,1,1,27,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
27,1001,10,2015-01-28,35,0.0,1,0.0,1,2,28,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
28,1001,10,2015-01-29,9,0.0,1,0.0,1,3,29,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
29,1001,10,2015-01-30,4,0.0,1,0.0,1,4,30,...,5.350,16,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23130,34,34,2015-04-01,4,0.0,1,0.6,4,2,91,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561
23131,34,34,2015-04-02,1,0.0,1,0.6,4,3,92,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561
23132,34,34,2015-04-03,3,0.0,1,0.8,4,4,93,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561
23133,34,34,2015-04-04,2,0.0,3,1.0,4,5,94,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23134,34,34,2015-04-05,3,1.0,3,1.0,4,6,95,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561
23135,34,34,2015-04-06,1,0.0,3,1.0,4,0,96,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23136,34,34,2015-04-07,5,0.0,1,0.5,4,1,97,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561
23137,34,34,2015-04-08,2,1.0,1,0.3,4,2,98,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561
23138,34,34,2015-04-09,0,0.0,1,0.3,4,3,99,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561
23139,34,34,2015-04-10,2,0.0,1,0.0,4,4,100,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561
23140,34,34,2015-04-11,2,0.0,2,0.0,4,5,101,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23141,34,34,2015-04-12,3,0.0,2,0.0,4,6,102,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561
23142,34,34,2015-04-13,1,0.0,1,0.0,4,0,103,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23143,34,34,2015-04-14,7,1.0,1,0.0,4,1,104,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561
23144,34,34,2015-04-15,1,0.0,1,0.0,4,2,105,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561
23145,34,34,2015-04-16,0,0.0,1,0.0,4,3,106,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561
23146,34,34,2015-04-17,3,2.0,1,0.0,4,4,107,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561
23147,34,34,2015-04-18,1,0.0,2,0.0,4,5,108,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23148,34,34,2015-04-19,2,2.0,2,0.0,4,6,109,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561
23149,34,34,2015-04-20,5,1.0,1,0.0,4,0,110,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23150,34,34,2015-04-21,1,0.0,1,0.0,4,1,111,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561
23151,34,34,2015-04-22,3,2.0,1,0.0,4,2,112,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561
23152,34,34,2015-04-23,1,0.0,1,0.0,4,3,113,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561
23153,34,34,2015-04-24,2,1.0,1,0.0,4,4,114,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561
23154,34,34,2015-04-25,4,0.0,2,0.0,4,5,115,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23155,34,34,2015-04-26,2,0.0,2,0.0,4,6,116,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561
23156,34,34,2015-04-27,2,0.0,1,0.0,4,0,117,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561
23157,34,34,2015-04-28,4,1.0,1,0.6,4,1,118,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561
23158,34,34,2015-04-29,12,9.0,1,0.6,4,2,119,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561
23159,34,34,2015-04-30,4,0.0,1,0.8,4,3,120,...,2.425,15,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561

In [3]:
train_new.loc[:,'saleCount_min'] = train_new['saleCount_mean'] - 2 * train_new['saleCount_std']
train_new.loc[:,'saleCount_max'] = train_new['saleCount_mean'] + 2 * train_new['saleCount_std']
train_new['saleCount_max'] = np.ceil(train_new['saleCount_max'])
train_new

,Class,parClass,SaleDate,saleCount,Coupon,holidayCluster,disHoliday,month,dayOfWeek,dayOfYear,...,holDaySaleCount_min,wkHolRatio,bonusRatio,bonusHolRatio,bonusNotHolRatio,bonusWeekProb,saleCount_mean,saleCount_std,saleCount_min,saleCount_max
0,1001,10,2015-01-01,3,0.0,3,1.0,1,3,1,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
1,1001,10,2015-01-02,6,0.0,3,1.0,1,4,2,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
2,1001,10,2015-01-03,7,0.0,3,1.0,1,5,3,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
3,1001,10,2015-01-04,5,0.0,1,0.5,1,6,4,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
4,1001,10,2015-01-05,9,0.0,1,0.3,1,0,5,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
5,1001,10,2015-01-06,5,0.0,1,0.3,1,1,6,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
6,1001,10,2015-01-07,28,0.0,1,0.0,1,2,7,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
7,1001,10,2015-01-08,7,0.0,1,0.0,1,3,8,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
8,1001,10,2015-01-09,4,0.0,1,0.0,1,4,9,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
9,1001,10,2015-01-10,4,0.0,2,0.0,1,5,10,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
10,1001,10,2015-01-11,3,0.0,2,0.0,1,6,11,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
11,1001,10,2015-01-12,12,0.0,1,0.0,1,0,12,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
12,1001,10,2015-01-13,5,0.0,1,0.0,1,1,13,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
13,1001,10,2015-01-14,16,0.0,1,0.0,1,2,14,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
14,1001,10,2015-01-15,9,0.0,1,0.0,1,3,15,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
15,1001,10,2015-01-16,9,0.0,1,0.0,1,4,16,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
16,1001,10,2015-01-17,3,0.0,2,0.0,1,5,17,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
17,1001,10,2015-01-18,5,0.0,2,0.0,1,6,18,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
18,1001,10,2015-01-19,4,0.0,1,0.0,1,0,19,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
19,1001,10,2015-01-20,9,0.0,1,0.0,1,1,20,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
20,1001,10,2015-01-21,25,0.0,1,0.0,1,2,21,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
21,1001,10,2015-01-22,6,0.0,1,0.0,1,3,22,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
22,1001,10,2015-01-23,7,0.0,1,0.0,1,4,23,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
23,1001,10,2015-01-24,2,0.0,2,0.0,1,5,24,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
24,1001,10,2015-01-25,5,0.0,2,0.0,1,6,25,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
25,1001,10,2015-01-26,13,0.0,1,0.0,1,0,26,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
26,1001,10,2015-01-27,12,0.0,1,0.0,1,1,27,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
27,1001,10,2015-01-28,35,0.0,1,0.0,1,2,28,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
28,1001,10,2015-01-29,9,0.0,1,0.0,1,3,29,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
29,1001,10,2015-01-30,4,0.0,1,0.0,1,4,30,...,0,3.330233,0.0000,0.0000,0.0000,0.000000,7.750000,6.038045,-4.326089,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23130,34,34,2015-04-01,4,0.0,1,0.6,4,2,91,...,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561,-2.363456,8.0
23131,34,34,2015-04-02,1,0.0,1,0.6,4,3,92,...,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561,-2.363456,8.0
23132,34,34,2015-04-03,3,0.0,1,0.8,4,4,93,...,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561,-2.363456,8.0
23133,34,34,2015-04-04,2,0.0,3,1.0,4,5,94,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23134,34,34,2015-04-05,3,1.0,3,1.0,4,6,95,...,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561,-2.363456,8.0
23135,34,34,2015-04-06,1,0.0,3,1.0,4,0,96,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23136,34,34,2015-04-07,5,0.0,1,0.5,4,1,97,...,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561,-2.363456,8.0
23137,34,34,2015-04-08,2,1.0,1,0.3,4,2,98,...,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561,-2.363456,8.0
23138,34,34,2015-04-09,0,0.0,1,0.3,4,3,99,...,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561,-2.363456,8.0
23139,34,34,2015-04-10,2,0.0,1,0.0,4,4,100,...,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561,-2.363456,8.0
23140,34,34,2015-04-11,2,0.0,2,0.0,4,5,101,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23141,34,34,2015-04-12,3,0.0,2,0.0,4,6,102,...,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561,-2.363456,8.0
23142,34,34,2015-04-13,1,0.0,1,0.0,4,0,103,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23143,34,34,2015-04-14,7,1.0,1,0.0,4,1,104,...,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561,-2.363456,8.0
23144,34,34,2015-04-15,1,0.0,1,0.0,4,2,105,...,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561,-2.363456,8.0
23145,34,34,2015-04-16,0,0.0,1,0.0,4,3,106,...,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561,-2.363456,8.0
23146,34,34,2015-04-17,3,2.0,1,0.0,4,4,107,...,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561,-2.363456,8.0
23147,34,34,2015-04-18,1,0.0,2,0.0,4,5,108,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23148,34,34,2015-04-19,2,2.0,2,0.0,4,6,109,...,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561,-2.363456,8.0
23149,34,34,2015-04-20,5,1.0,1,0.0,4,0,110,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23150,34,34,2015-04-21,1,0.0,1,0.0,4,1,111,...,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561,-2.363456,8.0
23151,34,34,2015-04-22,3,2.0,1,0.0,4,2,112,...,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561,-2.363456,8.0
23152,34,34,2015-04-23,1,0.0,1,0.0,4,3,113,...,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561,-2.363456,8.0
23153,34,34,2015-04-24,2,1.0,1,0.0,4,4,114,...,0,2.122449,0.4037,0.3243,0.4414,0.112360,2.541667,2.452561,-2.363456,8.0
23154,34,34,2015-04-25,4,0.0,2,0.0,4,5,115,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23155,34,34,2015-04-26,2,0.0,2,0.0,4,6,116,...,0,2.122449,0.4037,0.3243,0.4414,0.123596,2.541667,2.452561,-2.363456,8.0
23156,34,34,2015-04-27,2,0.0,1,0.0,4,0,117,...,0,2.122449,0.4037,0.3243,0.4414,0.089888,2.541667,2.452561,-2.363456,8.0
23157,34,34,2015-04-28,4,1.0,1,0.6,4,1,118,...,0,2.122449,0.4037,0.3243,0.4414,0.146067,2.541667,2.452561,-2.363456,8.0
23158,34,34,2015-04-29,12,9.0,1,0.6,4,2,119,...,0,2.122449,0.4037,0.3243,0.4414,0.359551,2.541667,2.452561,-2.363456,8.0
23159,34,34,2015-04-30,4,0.0,1,0.8,4,3,120,...,0,2.122449,0.4037,0.3243,0.4414,0.067416,2.541667,2.452561,-2.363456,8.0

#### 限制最大值

In [4]:
max_bool = train_new['saleCount_max'] < train_new['saleCount']
train_new['saleCount'][max_bool] = train_new['saleCount_max'][max_bool]

In [5]:
train_new['saleCount'].value_counts()

0      14162
1       2745
2       1440
3        887
4        574
5        515
6        379
7        279
8        253
9        216
10       161
11       123
12       122
14       101
13        96
16        55
18        54
15        53
17        51
21        36
20        35
19        33
24        28
27        25
23        24
26        23
28        20
42        18
43        16
22        16
       ...
153        2
137        2
121        2
120        2
166        2
103        2
102        2
116        2
70         2
133        2
138        1
100        1
157        1
172        1
132        1
148        1
123        1
202        1
170        1
122        1
177        1
169        1
98         1
149        1
197        1
147        1
151        1
135        1
119        1
183        1
Name: saleCount, Length: 159, dtype: int64

#### 限制最小值

In [6]:
neg_bool = train_new['saleCount_min'] < 0
train_new['saleCount_min'][neg_bool] = 0

In [7]:
min_bool = train_new['saleCount_min'] > train_new['saleCount']
train_new['saleCount'][min_bool] = train_new['saleCount_min'][min_bool]
train_new['saleCount'] = np.ceil(train_new['saleCount'])

In [8]:
min_bool = train_new['saleCount_min'] > train_new['saleCount']
train_new['saleCount'].value_counts()

0.0      14133
1.0       2756
2.0       1439
3.0        886
4.0        574
5.0        520
6.0        384
7.0        279
8.0        253
9.0        216
10.0       161
11.0       123
12.0       122
14.0       100
13.0        96
16.0        55
18.0        54
15.0        53
17.0        50
21.0        43
20.0        35
19.0        32
24.0        28
27.0        25
23.0        24
26.0        23
28.0        20
30.0        20
42.0        18
43.0        16
         ...
112.0        2
121.0        2
176.0        2
137.0        2
97.0         2
108.0        2
116.0        2
140.0        2
133.0        2
130.0        2
138.0        1
169.0        1
177.0        1
119.0        1
197.0        1
149.0        1
100.0        1
172.0        1
147.0        1
132.0        1
122.0        1
123.0        1
148.0        1
157.0        1
98.0         1
202.0        1
183.0        1
151.0        1
170.0        1
135.0        1
Name: saleCount, Length: 159, dtype: int64